import type { Metadata } from "next";
import Providers from "@/components/providers";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { SiteHeader } from "@/components/layout/site-header"

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="sticky top-0 z-50 bg-yellow-100 border-b border-yellow-200 py-2 text-center text-2xl font-medium text-yellow-800">
          ActiviaBook is currently in Beta. Please report any issues.
        </div>
        <Providers>
          <SiteHeader />
          <main>
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
